### ISSUE TITLE
ROADMAP of Video Diffusion

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/Video-Diffusion-WebUI#21]
- [ ] https://github.com/kadirnar/Video-Diffusion-WebUI/issues/22
- [ ] https://github.com/kadirnar/Video-Diffusion-WebUI/issues/18
- [ ] https://github.com/kadirnar/Video-Diffusion-WebUI/issues/7
